# -*- coding: utf-8 -*-
"""Web Scrapping v0.0.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WtnvYBKYZ5dDr-Rj1MhWC3RtP6IPB96p
"""

pip install requests beautifulsoup4 googlesearch-python

from googlesearch import search
import requests
from bs4 import BeautifulSoup
import re
import csv

# Frases para buscar en Google
busquedas = [
    "colegio contacto correo site:.ec",
    "colegio privado Quito correo contacto",
    "colegio católico Guayaquil contacto email",
    "institución educativa correo site:.ec",
]

# Guardar resultados
resultados = []

# Buscar enlaces en Google
for query in busquedas:
    print(f"🔍 Buscando: {query}")
    enlaces = search(query, num_results=10, lang="es")

    for url in enlaces:
        print(f"➡️ Analizando: {url}")
        try:
            res = requests.get(url, timeout=10)
            soup = BeautifulSoup(res.text, "html.parser")
            texto = soup.get_text()
            correos = set(re.findall(r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}", texto))
            nombre = soup.title.string.strip() if soup.title else "Sin título"

            for correo in correos:
                resultados.append({
                    "nombre": nombre,
                    "correo": correo,
                    "web": url
                })
        except Exception as e:
            print(f"❌ Error en {url}: {e}")

# Guardar en CSV
with open("correos_colegios_ecuador.csv", "w", newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=["nombre", "correo", "web"])
    writer.writeheader()
    writer.writerows(resultados)

print(f"✅ Proceso terminado. Se encontraron {len(resultados)} correos.")

from google.colab import files
files.download("correos_colegios_ecuador.csv")